version: 2
jobs:
  build:
    working_directory: ~/frontRFID
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - restore_cache:
          key: frontRFID-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: frontRFID-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
       # Lint the source code
      - run:
          name: Linting
          command: npm run lint
